# Generated by Django 4.2.11 on 2024-08-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_contactform_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
