# Generated by Django 4.2.11 on 2024-08-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_contact_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
