# Generated by Django 4.2.11 on 2024-08-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_delete_contactform_delete_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField(max_length=1000)),
                ('comment', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=300, unique=True)),
                ('recipe_description', models.TextField(max_length=1000, unique=True)),
                ('recipe_ingredients', models.TextField(max_length=2000)),
                ('recipe_steps', models.TextField(max_length=2000)),
            ],
        ),
    ]
