# Generated by Django 4.2.11 on 2024-04-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/default_profile_izly1f', upload_to='images/'),
        ),
    ]
