# Generated by Django 4.2.11 on 2024-08-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('food_pic', models.ImageField(blank=True, default='food_pic/default_profle_izly1f', upload_to='food_pic/')),
                ('ingredients', models.TextField(max_length=4096)),
            ],
        ),
    ]
